version: "3.7"

services:
  mysql:
    container_name: mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - "./:/home"
      - "./database_scripts/setup_mysql_dev.sql:/docker-entrypoint-initdb.d/setup_mysql_dev.sql"
      - "./database_scripts/setup_mysql_test.sql:/docker-entrypoint-initdb.d/setup_mysql_test.sql"
